# OKX API 配置
okx:
  base_url: "https://www.okx.com"
  # API 认证信息
  api:
    # 模拟账户 apply api key in www.okx.com
    api_key: "f114d4f4-0bdb7e675c-1492e-4f9b-a9211"
    secret_key: "693C5EA261B05777BA5431DF22CD0BC6D01"
    passphrase: "12345678"
    is_simulated: false

# 日志配置
logging:
  level: "debug"  # debug, info, warn, error
  format: "text"  # text, json